function Germanvocab = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  GERMANVOCAB = IMPORTFILE(FILE) reads data from the first worksheet in
%  the Microsoft Excel spreadsheet file named FILE.  Returns the data as
%  a table.
%
%  GERMANVOCAB = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  GERMANVOCAB = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  Germanvocab = importfile("E:\Notes\Matlab\Lecture Study\Matlab exercises and project\Matlab_exercises_and_project\Mini_project_German_Learning_Tool\German_vocab.xlsx", "Sheet1", [1, 27]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 09-Oct-2022 12:20:48

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [1, 27];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 2);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":B" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["anhalten", "toStop"];
opts.VariableTypes = ["string", "string"];

% Specify variable properties
opts = setvaropts(opts, ["anhalten", "toStop"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["anhalten", "toStop"], "EmptyFieldRule", "auto");

% Import the data
Germanvocab = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":B" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    Germanvocab = [Germanvocab; tb]; %#ok<AGROW>
end

end