function Germanvocabnew = importfilenew(workbookFile, sheetName, dataLines)
%IMPORTFILE1 Import data from a spreadsheet
%  GERMANVOCABNEW = IMPORTFILE1(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  GERMANVOCABNEW = IMPORTFILE1(FILE, SHEET) reads from the specified
%  worksheet.
%
%  GERMANVOCABNEW = IMPORTFILE1(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  Germanvocabnew = importfile1("E:\Notes\Matlab\Lecture Study\Matlab exercises and project\Matlab_exercises_and_project\Mini_project_German_Learning_Tool\German_vocab_new.xlsx", "Sheet1", [1, 16]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 12-Oct-2022 18:22:56

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [1, 16];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 3);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":C" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["hbsh", "pretty", "VarName3"];
opts.VariableTypes = ["string", "string", "double"];

% Specify variable properties
opts = setvaropts(opts, ["hbsh", "pretty"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["hbsh", "pretty"], "EmptyFieldRule", "auto");

% Import the data
Germanvocabnew = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":C" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    Germanvocabnew = [Germanvocabnew; tb]; %#ok<AGROW>
end

end