function Insurrancedata = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  INSURRANCEDATA = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  INSURRANCEDATA = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  Insurrancedata = importfile("E:\Notes\Matlab\Lecture Study\Matlab exercises and project\Matlab_exercises_and_project\Mini_project_Insurrance_predictor\Insurrance_data.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 02-Oct-2022 11:05:12

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Age", "EstimatedSalary", "Purchased"];
opts.SelectedVariableNames = ["Age", "EstimatedSalary", "Purchased"];
opts.VariableTypes = ["string", "string", "double", "double", "categorical"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Purchased"], "EmptyFieldRule", "auto");

% Import the data
Insurrancedata = readtable(filename, opts);

end