% y = [3 5 7 17 6 4 2];
% x = [1 2 3 4 5 6 7];
% z = [-0.1 -0.2 -0.3 -0.4 -0.5 -0.6 -0.7];
% plot(x, y)
% figure, plot(x, z)

% y = [3 5 7 17 6 4 2];
% x = [1 2 3 4 5 6 7];
% z = [-0.1 -0.2 -0.3 -0.4 -0.5 -0.6 -0.7];
% plot(x, y)
% xlabel('X- axis')
% ylabel('Y- axis')
% figure, plot(x, z)
% xlabel('X- axis')
% ylabel('Z- axis')
%{
y = [3 5 7 17 6 4 2];
x = [1 2 3 4 5 6 7];
z = [-0.1 -0.2 -0.3 -0.4 -0.5 -0.6 -0.7];

createfigure(x,y)

function createfigure(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data Y1:  vector of y data

%  Auto-generated by MATLAB on 02-Aug-2022 15:56:49

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'DisplayName','line','Marker','|','LineStyle','--',...
    'Color',[1 0 0]);

% Create ylabel
ylabel('Y axis');

% Create xlabel
xlabel('X axis');

% Create title
title('Graph');

box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'Color',[0.678431391716003 0.921568632125854 1],'XColor',...
    [0.850980401039124 0.325490206480026 0.0980392172932625],'YColor',...
    [0.850980401039124 0.325490206480026 0.0980392172932625],'ZColor',...
    [0.850980401039124 0.325490206480026 0.0980392172932625]);
% Create legend
legend(axes1,'show');
end
%}
